apiVersion: batch/v1
kind: Job
metadata:
  name: pricelist-config-hook
  namespace: pricelist
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: alpine:latest
        command: 
          - "sleep"
          - "12"
      restartPolicy: Never
  backoffLimit: 2
